-- =========================================================
-- 1. ADMINISTRADOR
-- =========================================================

CREATE TABLE administrador (
    id_administrador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    nivel_acesso VARCHAR(50) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. PROFESSOR
-- =========================================================

CREATE TABLE professor (
    id_professor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    chave_pix VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 3. ALUNO
-- =========================================================

CREATE TABLE aluno (
    id_aluno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150),
    telefone VARCHAR(20),
    data_entrada DATE NOT NULL,
    data_saida DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_aluno_datas
        CHECK (
            data_saida IS NULL
            OR data_saida >= data_entrada
        )
);


-- =========================================================
-- 4. INSTRUMENTO
-- =========================================================

CREATE TABLE instrumento (
    id_instrumento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 5. MATERIA
-- =========================================================

CREATE TABLE materia (
    id_materia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_instrumento BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_materia_instrumento
        FOREIGN KEY (id_instrumento)
        REFERENCES instrumento (id_instrumento)
);


-- =========================================================
-- 6. PROFESSOR_MATERIA
-- =========================================================

CREATE TABLE professor_materia (
    id_professor_materia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_professor BIGINT NOT NULL,
    id_materia BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_professor_materia_professor
        FOREIGN KEY (id_professor)
        REFERENCES professor (id_professor),

    CONSTRAINT fk_professor_materia_materia
        FOREIGN KEY (id_materia)
        REFERENCES materia (id_materia),

    CONSTRAINT uk_professor_materia
        UNIQUE (id_professor, id_materia)
);


-- =========================================================
-- 7. MATRICULA
-- =========================================================

CREATE TABLE matricula (
    id_matricula BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aluno BIGINT NOT NULL,
    id_professor_materia BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    valor_mensal NUMERIC(10,2) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_matricula_aluno
        FOREIGN KEY (id_aluno)
        REFERENCES aluno (id_aluno),

    CONSTRAINT fk_matricula_professor_materia
        FOREIGN KEY (id_professor_materia)
        REFERENCES professor_materia (id_professor_materia),

    CONSTRAINT chk_matricula_valor
        CHECK (valor_mensal >= 0),

    CONSTRAINT chk_matricula_datas
        CHECK (
            data_fim IS NULL
            OR data_fim >= data_inicio
        )
);


-- =========================================================
-- 8. STATUS_PAGAMENTO
-- =========================================================

CREATE TABLE status_pagamento (
    id_status_pagamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL UNIQUE
);


-- =========================================================
-- 9. PAGAMENTO_ALUNO
-- =========================================================

CREATE TABLE pagamento_aluno (
    id_pagamento_aluno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_matricula BIGINT NOT NULL,
    id_administrador_recebedor BIGINT,
    id_status_pagamento BIGINT NOT NULL,
    valor NUMERIC(10,2) NOT NULL,
    competencia DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento TIMESTAMP,
    observacao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pagamento_aluno_matricula
        FOREIGN KEY (id_matricula)
        REFERENCES matricula (id_matricula),

    CONSTRAINT fk_pagamento_aluno_administrador
        FOREIGN KEY (id_administrador_recebedor)
        REFERENCES administrador (id_administrador),

    CONSTRAINT fk_pagamento_aluno_status
        FOREIGN KEY (id_status_pagamento)
        REFERENCES status_pagamento (id_status_pagamento),

    CONSTRAINT uk_pagamento_aluno_competencia
        UNIQUE (id_matricula, competencia),

    CONSTRAINT chk_pagamento_aluno_valor
        CHECK (valor >= 0)
);


-- =========================================================
-- 10. PAGAMENTO_PROFESSOR
-- =========================================================

CREATE TABLE pagamento_professor (
    id_pagamento_professor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_professor BIGINT NOT NULL,
    id_administrador_pagador BIGINT,
    id_status_pagamento BIGINT NOT NULL,
    competencia DATE NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL,
    data_pagamento TIMESTAMP,
    observacao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pagamento_professor_professor
        FOREIGN KEY (id_professor)
        REFERENCES professor (id_professor),

    CONSTRAINT fk_pagamento_professor_administrador
        FOREIGN KEY (id_administrador_pagador)
        REFERENCES administrador (id_administrador),

    CONSTRAINT fk_pagamento_professor_status
        FOREIGN KEY (id_status_pagamento)
        REFERENCES status_pagamento (id_status_pagamento),

    CONSTRAINT chk_pagamento_professor_valor
        CHECK (valor_total >= 0)
);


-- =========================================================
-- 11. PAGAMENTO_PROFESSOR_ITEM
-- =========================================================

CREATE TABLE pagamento_professor_item (
    id_pagamento_professor_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pagamento_professor BIGINT NOT NULL,
    id_pagamento_aluno BIGINT NOT NULL,
    valor_repasse NUMERIC(10,2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pagamento_professor_item_pagamento_professor
        FOREIGN KEY (id_pagamento_professor)
        REFERENCES pagamento_professor (id_pagamento_professor),

    CONSTRAINT fk_pagamento_professor_item_pagamento_aluno
        FOREIGN KEY (id_pagamento_aluno)
        REFERENCES pagamento_aluno (id_pagamento_aluno),

    CONSTRAINT uk_pagamento_professor_item_pagamento_aluno
        UNIQUE (id_pagamento_aluno),

    CONSTRAINT chk_pagamento_professor_item_valor
        CHECK (valor_repasse >= 0)
);
